name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          artifact-name: packages-windows
        - os: ubuntu-22.04
          artifact-name: packages-linux
        - os: macos-13
          artifact-name: packages-macos

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true

    - name: Install tools
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get -yq install mono-complete dos2unix fakeroot libunwind8

    - name: Install tools
      if: runner.os == 'macOS'
      run: brew install mono dos2unix

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
          10.0.x

    - name: Version Information
      run: |
        dotnet --info
        try { msbuild -version } catch { }
        try { mono --version } catch { }
      shell: pwsh

    - name: Build
      run: pwsh make.ps1

    - name: Package
      run: pwsh make.ps1 package

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact-name }}
        path: Package/Release/Packages

    - name: Test (net45)
      run: ./make.ps1 -frameworks net45 test-all
      shell: pwsh

    - name: Test (net8.0)
      run: ./make.ps1 -frameworks net8.0 test-all
      shell: pwsh

    - name: Test (net10.0)
      run: ./make.ps1 -frameworks net10.0 test-all
      shell: pwsh
