name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
          10.0.x

    - name: Version Information
      run: |
        dotnet --info
        try { msbuild -version } catch { }
        try { mono --version } catch { }
      shell: pwsh

    - name: Build
      run: pwsh make.ps1

    - name: Package
      run: pwsh make.ps1 package

    - uses: actions/upload-artifact@v7
      with:
        name: packages-windows
        path: Package/Release/Packages

    - name: Test (net462)
      run: ./make.ps1 -frameworks net45 test-all
      shell: pwsh
